# Zurg configuration version
zurg: v1

token: {{token}}

host: "[::]" # do not change this if you are running it inside a docker container
port: 9999 # do not change this if you are running it inside a docker container
concurrent_workers: 200
check_for_changes_every_secs: 15


enable_repair: true # BEWARE! THERE CAN ONLY BE 1 INSTANCE OF ZURG THAT SHOULD REPAIR YOUR TORRENTS
retain_folder_name_extension: false # if true, zurg won't modify the filenames from real-debrid
retain_rd_torrent_name: true # if true, it will strictly follow RD API returned torrent name which should make this more compatible with rdt-client
on_library_update: |
  for arg in "$@"
  do
      echo "detected update on: $arg"
  done

network_buffer_size: 1048576 # 1 MiB

# List of directory definitions and their filtering rules
directories:
  torrents:
    group: 1           # notice the group now is "all", which means it will have all the torrents of shows+movies combined because this directory is alone in this group
    filters:
      - regex: /.*/
