---
- hosts: localhost
  gather_facts: false

  tasks:

    - name: Check if plex_autoscan.service exists
      stat:
        path: "/etc/systemd/system/plex_autoscan.service"
      register: plex_autoscan_service

    - name: Check if drive1.anchor exists
      stat:
        path: "/home/{{ lookup('env','USER') }}/local/drive1.anchor"
      register: anchor_service

    - name: create file anchor
      shell: |
        touch /home/{{ lookup('env','USER') }}/local/drive1.anchor
      when: not anchor_service.stat.exists

    - name: Service Tasks
      block:

      - name: Populate Service Facts
        service_facts:

      - name: Get plex_autoscan service state
        set_fact:
          plex_autoscan_service_running: "{{ (services['plex_autoscan.service'] is defined) and (services['plex_autoscan.service']['state'] == 'running') }}"

      - name: Stop plex_autoscan service
        become: yes
        systemd:
          name: plex_autoscan
          state: stopped
          enabled: no
        when: plex_autoscan_service_running

      - name: delete plex_autoscan folder, file
        become: yes
        file:
          path: "{{ item }}"
          state: absent
        with_items:
        - /etc/systemd/system/plex_autoscan.service
        - "/home/{{ lookup('env','USER') }}/scripts/plex_autoscan"
        when: plex_autoscan_service_running

      when: plex_autoscan_service.stat.exists

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'autoscan'
        image: 'cloudb0x/autoscan'

    - name: Creating paths
      file: "path={{item}} state=directory mode=0775 owner={{ lookup('env','MYUID') }} group={{ lookup('env','MYGID') }}"
      with_items:
        - "/home/{{ lookup('env','USER') }}/scripts/{{pgrole}}"
        
    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - "/home/{{ lookup('env','USER') }}/scripts/{{pgrole}}:/config"
          - "/home/{{ lookup('env','USER') }}:/home/{{ lookup('env','USER') }}:ro"
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: "{{ lookup('env','MYUID') }}"
          PGID: "{{ lookup('env','MYGID') }}"
          AUTOSCAN_VERBOSITY: '2'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        ports:
          - '127.0.0.1:3030:3030'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started

    - name: Import default config
      template:
        src: "{{ settings.source }}/includes/config/roles/autoscan/templates/config.yml.j2"
        dest: "/home/{{ lookup('env','USER') }}/scripts/autoscan/config.yml"
        mode: 0600
        force: yes



