# Import the theme
theme: jekyll-theme-chirpy

# boolean type, the global switch for TOC in posts.
toc: true

# remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-multiple-languages-plugin
title: ssdv2
description: Simple Seedbox Docker

languages: ["fr", "en"]

baseurl: /ssdv2

defaultLang: fr
languageNames:
  fr: Fran√ßais
  en: English