remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme
- jekyll-multiple-languages-plugin
title: Kubeseed
description: Une seedbox sous Kubernetes

languages: ["fr", "en"]

baseurl: /kubeseed

defaultLang: fr
languageNames:
  fr: Fran√ßais
  en: English

